### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by rluu1405** [escobaros-dos/mealplanner#1]
To Complete
-Try to complete SRS
   introduction, purpose, basic information
-Create UML (download ArgoUML)
    class diagram
    GUI flow diagram
    ????
-Investigate/Decide on Design Pattern for project

-Familiarize with Qt and Git

**Comment by Raychill** [comment]
Completed to date:
SRS:
   Basic Use cases
Choose DataBase
    QT data base

**Comment by SSJ420BlazeIt** [comment]
Reminder to myself to bring up Modal vs Modal-less approach in QT.

**Comment by SSJ420BlazeIt** [comment]
Doug suggested: 2 databases
1 for reciepes
1 for ingrediants
