### ISSUE TITLE
db

### ISSUE THREAD

**Issue by rluu1405** [escobaros-dos/mealplanner#4]
should we have the dbs, how ever many we decide to have, be initially be opened in the main window, or have them be opening in the mpdatabase class

-figuring out how to format the table/tables

-one database multiple tables (ingredients table, recipe table, meal table)?

**Comment by christmasCake232** [comment]
Why not one db with many different tables?

**Comment by rluu1405** [comment]
no it would make more sense having one db and multiple tables
